spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restapi
    username: su
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    driver-class-name: com.mysql.cj.jdbc.Driver
    change-log: classpath:ChangeLog.xml
    url: jdbc:mysql://localhost:3306/restapi
    enabled: false
    user: su
    password:

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  sql:
    init:
      mode: always

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
